services:
  contact_application:
    image: contactlist:v1
    ports:
      - "9000:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dockercompose
    depends_on:
      - contact_db
  contact_db:
    image: postgres
    ports:
      - "5000:5432"
    environment:
      POSTGRES_PASSWORD: postgres

